version: "3.7"
services:
  proyectos-backend-micro:
    container_name: proyectos-backend-micro
    image: proyectos-backend-micro:latest
    build:
      context: .
    ports:
      - "4002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4002
    networks:

  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:latest
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectos-app
networks:
  proyectos-app:
